# Generated by Django 4.0 on 2022-05-13 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='github_users',
            new_name='Holidays',
        ),
    ]
