# Generated by Django 4.0.4 on 2022-05-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_github_users_holidays'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidays',
            options={'ordering': ['country_code', '-id']},
        ),
        migrations.AddField(
            model_name='holidays',
            name='country_code',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
