# Generated by Django 4.0 on 2022-05-18 02:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_holidays_options_holidays_country_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='holidays',
            options={'ordering': ['country_code', 'date']},
        ),
    ]
